#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scopt_2.12
Version  : 3.7.0
Release  : 3
URL      : https://repo1.maven.org/maven2/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.jar
Source0  : https://repo1.maven.org/maven2/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.jar
Source1  : https://repo.maven.apache.org/maven2/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.pom
Source3  : https://repo1.maven.org/maven2/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-scopt_2.12-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scopt_2.12 package.
Group: Data

%description data
data components for the mvn-scopt_2.12 package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.7.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.5.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.5.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.7.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.jar
/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.pom
/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.jar
/usr/share/java/.m2/repository/com/github/scopt/scopt_2.12/3.7.0/scopt_2.12-3.7.0.pom
